name: Fly Deploy
on:
  push:
    branches:
      - main
env:
  FLY_API_TOKEN: "-bto021PFk7C348X1Qq9em1lmQXYzk8YA6w-ggCXmag"
jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: flyctl deploy --remote-only
